---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: check-json
      # - id: pretty-format-json
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.40.1
    hooks:
      - id: cfn-lint
        files: ^cloudformation/.*\.ya?ml$
        exclude: ^(cloudformation/parameters/|state-machines/|cloudformation/sc-product-trigger\.yaml$)
        # ignore_checks: W2001,W1032,E3012,E3032
        # args: [--format=parseable]
  - repo: https://github.com/psf/black
    rev: 25.9.0 # The version of black to use
    hooks:
      - id: black
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.483 # change to tag or sha
    hooks:
      - id: checkov
        files: \.(y(a)?ml|json)$
        entry: checkov -d CloudFormation --quiet --skip-check CKV_AWS_115,CKV_AWS_116
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix, --disable, MD013, MD033, MD040, MD041]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        args: [--verbose]
